# The file `cats.ttl` consists of leaf concepts plus their Wikipedia categories.
# The categories have been manually filtered to yield the set
# `cats_filtered.ttl`. This query uses the latter to eliminate
# unwanted categories from the former.
#
# @title Build new RDF graph using categories from pre-filtered list



PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#> 
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

CONSTRUCT
{ ?s dcterms:subject ?cat .
  ?cat rdf:type skos:Concept . }
WHERE 
{ ?s dcterms:subject ?cat .
  ?cat rdf:type skos:Concept . 
}

